services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput"
    startCommand: "gunicorn dukan.wsgi:application --preload"
    routes:
      - type: static
        name: static
        path: /static/
        source: staticfiles/
