# Generated by Django 5.2.4 on 2026-08-13 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dabeli", "0005_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "css_class",
                    models.CharField(
                        help_text="CSS class for filtering (e.g., 'burger', 'pizza')",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="menu_images/"),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        help_text="Fallback for static images",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("order_link", models.URLField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="dabeli.category",
                    ),
                ),
            ],
        ),
    ]
