# Generated by Django 5.2.4 on 2026-08-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dabeli", "0006_category_menuitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_title", models.CharField(default="TASTY", max_length=200)),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="Treat Yourself: Relish Surat's tastiest Fast Food at Wallet-Friendly Prices!",
                        max_length=200,
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="site_images/"),
                ),
                (
                    "hero_image_url",
                    models.CharField(
                        blank=True,
                        help_text="Fallback for static images",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "about_title",
                    models.CharField(default="We Are Dinesh Dabeli", max_length=200),
                ),
                ("about_text", models.TextField()),
                (
                    "about_image",
                    models.ImageField(blank=True, null=True, upload_to="site_images/"),
                ),
                (
                    "about_image_url",
                    models.CharField(
                        blank=True,
                        help_text="Fallback for static images",
                        max_length=500,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("discount_text", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="offers/"),
                ),
                ("image_url", models.CharField(blank=True, max_length=500, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
