# Generated by Django 5.2.4 on 2026-08-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dabeli", "0007_homepagecontent_offer_menuitem_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        default="919876543210",
                        help_text="WhatsApp number with country code, e.g. 919876543210",
                        max_length=15,
                    ),
                ),
                (
                    "delivery_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=30.0,
                        help_text="Delivery charge in ₹",
                        max_digits=6,
                    ),
                ),
                (
                    "free_delivery_above",
                    models.DecimalField(
                        decimal_places=2,
                        default=200.0,
                        help_text="Free delivery for orders above this amount. Set to 0 to always charge.",
                        max_digits=6,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Discount percentage on total (0 for no discount)",
                        max_digits=5,
                    ),
                ),
                (
                    "discount_min_order",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Minimum order amount to apply discount",
                        max_digits=6,
                    ),
                ),
                (
                    "is_delivery_available",
                    models.BooleanField(
                        default=True, help_text="Enable/disable delivery orders"
                    ),
                ),
                (
                    "shop_open_message",
                    models.CharField(
                        blank=True, default="We're open! Order now.", max_length=200
                    ),
                ),
                (
                    "shop_closed_message",
                    models.CharField(
                        blank=True,
                        default="We're currently closed. Please try again later.",
                        max_length=200,
                    ),
                ),
                ("is_shop_open", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Shop Settings",
                "verbose_name_plural": "Shop Settings",
            },
        ),
    ]
