# Generated by Django 5.2.4 on 2026-08-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dabeli", "0008_shopsettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="css_class",
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Category name (e.g. Dabeli, Pizza, Burger)", max_length=100
            ),
        ),
    ]
