# Generated by Django 5.2.4 on 2026-08-14 06:58

from django.db import migrations
from django.utils.text import slugify


def fix_css_classes(apps, schema_editor):
    Category = apps.get_model('dabeli', 'Category')
    for category in Category.objects.all():
        category.css_class = slugify(category.name)
        category.save(update_fields=['css_class'])


class Migration(migrations.Migration):

    dependencies = [
        ("dabeli", "0009_alter_category_options_alter_category_css_class_and_more"),
    ]

    operations = [
        migrations.RunPython(fix_css_classes, migrations.RunPython.noop),
    ]
