# Generated by Django 4.2.19 on 2026-08-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dabeli", "0010_fix_category_css_classes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagecontent",
            name="about_image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="site_images/"
            ),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="hero_image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="site_images/"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="menu_images/"
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="offers/"
            ),
        ),
    ]
