# Generated by Django 4.2.19 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dabeli", "0011_alter_homepagecontent_about_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FranchiseInquiry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("city", models.CharField(max_length=100)),
                ("budget", models.CharField(blank=True, choices=[("under_5l", "Under ₹5 lakh"), ("5l_10l", "₹5–10 lakh"), ("10l_20l", "₹10–20 lakh"), ("above_20l", "Above ₹20 lakh")], max_length=20)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
