# Generated by Django 4.2.19 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dabeli", "0012_franchiseinquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="franchiseinquiry",
            name="locality",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
